import type { CampaignRequest, ExpenditureRequest, KycRequest } from './RequestTypes';

export const mockCampaignRequests: CampaignRequest[] = [
  {
    id: 'CR_0005',
    createdAt: '2026-02-08 14:20',
    status: 'PENDING',
    type: 'APPROVE_CAMPAIGN',
    campaignId: 201,
    campaignTitle: 'Emergency Food Relief',
    requesterName: 'Hung Thang',
    category: 'Relief',
    description: 'Providing immediate food assistance to families affected by the flood.',
    kycVerified: true,
    bankVerified: true,
  },
  {
    id: 'CR_0006',
    createdAt: '2026-02-08 15:30',
    status: 'PENDING',
    type: 'APPROVE_CAMPAIGN',
    campaignId: 202,
    campaignTitle: 'Education for All',
    requesterName: 'Minh Khôi',
    category: 'Education',
    description: 'Scholarships for underprivileged children in rural areas.',
    kycVerified: false,
    bankVerified: true,
  },
  {
    id: 'CR_0007',
    createdAt: '2026-02-08 16:45',
    status: 'PENDING',
    type: 'APPROVE_CAMPAIGN',
    campaignId: 203,
    campaignTitle: 'Clean Energy Project',
    requesterName: 'Thanh Hà',
    category: 'Environment',
    description: 'Installing solar panels in community centers.',
    kycVerified: true,
    bankVerified: false,
  },
  {
    id: 'CR_0001',
    createdAt: '2026-01-24 10:12',
    status: 'PENDING',
    type: 'WITHDRAWAL',
    campaignId: 101,
    campaignTitle: 'Warm Meals for Students',
    requesterName: 'Fund Owner #12',
    amount: 1200,
    note: 'Need payout for recent expenses',
    kycVerified: true,
    bankVerified: true,
  },
];

export const mockExpenditureRequests: ExpenditureRequest[] = [
  {
    id: 'ER_0001',
    createdAt: '2026-02-07 14:20',
    status: 'PENDING',
    type: 'EXPENDITURE',
    campaignId: 1,
    campaignTitle: 'Clean Water Wells in Rural Vietnam',
    requesterName: 'Owner #1',
    totalAmount: 1500,
    expenditureItems: [
      { description: 'PVC Pipes and fittings', quantity: 50, price: 10 },
      { description: 'Manual Water Pump', quantity: 2, price: 300 },
      { description: 'Cement bags', quantity: 20, price: 20 },
    ],
    justification: 'Necessary materials for the construction of the first two wells in Highland village. Prices are based on local vendor quotes.',
  },
  {
    id: 'ER_0002',
    createdAt: '2026-02-06 09:15',
    status: 'APPROVED',
    type: 'EXPENDITURE',
    campaignId: 4,
    campaignTitle: 'Rebuild Homes After Typhoon Yagi',
    requesterName: 'Owner #1',
    totalAmount: 3000,
    expenditureItems: [
      { description: 'Roofing metal sheets', quantity: 100, price: 20 },
      { description: 'Timber beams', quantity: 40, price: 25 },
    ],
    justification: 'Materials for rebuilding the roof of two heavily damaged houses in Quang Binh.',
  },
  {
    id: 'ER_0003',
    createdAt: '2026-02-05 16:45',
    status: 'REJECTED',
    type: 'EXPENDITURE',
    campaignId: 10,
    campaignTitle: 'Computers for Rural Schools Initiative',
    requesterName: 'Owner #2',
    totalAmount: 500,
    expenditureItems: [
      { description: 'Staff travel expenses', quantity: 1, price: 500 },
    ],
    justification: 'Travel costs for staff to visit school sites for assessment.',
  },
];

export const mockKycRequests: KycRequest[] = [
  {
    id: 'KYC_0001',
    createdAt: '2026-02-08 10:15',
    status: 'PENDING',
    type: 'KYC_VERIFICATION',
    userId: 2,
    idType: 'CCCD',
    idNumber: '012345678901',
    issueDate: '2022-01-15',
    expiryDate: '2032-01-15',
    issuePlace: 'Cục Cảnh sát QLHC về trật tự xã hội',
    idImageFront: 'https://images.unsplash.com/photo-1557124816-e9b7d5440de2?w=800&auto=format&fit=crop',
    idImageBack: 'https://images.unsplash.com/photo-1557124816-e9b7d5440de2?w=800&auto=format&fit=crop',
    selfieImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop',
  },
  {
    id: 'KYC_0002',
    createdAt: '2026-02-08 11:30',
    status: 'PENDING',
    type: 'KYC_VERIFICATION',
    userId: 5,
    idType: 'PASSPORT',
    idNumber: 'B1234567',
    issueDate: '2020-05-20',
    expiryDate: '2030-05-20',
    issuePlace: 'Cục Quản lý xuất nhập cảnh',
    idImageFront: 'https://images.unsplash.com/photo-1544254256-0740a325852f?w=800&auto=format&fit=crop',
    idImageBack: 'https://images.unsplash.com/photo-1544254256-0740a325852f?w=800&auto=format&fit=crop',
    selfieImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=800&auto=format&fit=crop',
  },
];


