import type { CampaignRequest } from './RequestTypes';

export const newFlowMockCampaigns: CampaignRequest[] = [
  {
    id: 'CAMP_NF_1',
    createdAt: '2026-04-20T10:30:00Z',
    status: 'PENDING',
    type: 'APPROVE_CAMPAIGN',
    campaignId: 9001,
    campaignTitle: 'Hỗ trợ vùng lũ miền Trung 2026',
    requesterName: 'NGUYEN VAN A',
    description: 'Huy động quỹ tổng để cung cấp nhu yếu phẩm, vận chuyển và phân phối cho 2.000 hộ dân.',
    category: 'Cứu trợ thiên tai',
    kycVerified: true,
    bankVerified: true,
    fundOwnerId: 101,
    newFlowData: {
      eligibility: {
        kycStatus: 'APPROVED',
        kycFullName: 'NGUYEN VAN A',
        bankInfo: {
          bankCode: 'MBB',
          bankName: 'Ngân hàng TMCP Quân Đội',
          accountHolderName: 'NGUYEN VAN A',
          accountNumber: '0123456789',
        },
        credibilityFiles: [
          { id: 'f1', name: 'ho-so-uy-tin-to-chuc.pdf', sizeKb: 824 },
          { id: 'f2', name: 'xac-nhan-dia-phuong.pdf', sizeKb: 622 },
        ],
        credibilityPitch:
          'Tổ chức đã triển khai 12 chương trình cứu trợ trong 3 năm gần nhất, có báo cáo tài chính công khai và đối tác địa phương xác thực.',
      },
      campaignImages: [
        { id: 'img1', url: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?w=600&h=400&fit=crop' },
        { id: 'img2', url: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=600&h=400&fit=crop' },
        { id: 'img3', url: 'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=600&h=400&fit=crop' },
      ],
      coverImageId: 'img1',
      objective:
        'Huy động quỹ tổng để cung cấp nhu yếu phẩm (gạo, nước sạch, thuốc), vận chuyển và tổ chức phân phối an toàn cho 2.000 hộ dân bị ảnh hưởng lũ lụt tại Quảng Bình và Quảng Trị.',
      targetAmount: 1_000_000_000,
      startDate: '2026-04-25',
      endDate: '2026-05-25',
      region: 'Quảng Bình — Quảng Trị',
      beneficiaryType: 'Hộ gia đình bị ảnh hưởng trực tiếp',
      thankMessage: 'Cảm ơn bạn đã cùng chúng tôi giữ an toàn cho người dân vùng lũ.',
      milestones: [
        {
          id: 'm1',
          title: 'Đợt 1 — Cứu trợ khẩn cấp',
          description: 'Cung cấp nhu yếu phẩm cơ bản cho 800 hộ đầu tiên.',
          plannedAmount: 350_000_000,
          releaseCondition: 'Xác nhận danh sách hộ nhận từ chính quyền địa phương.',
        },
        {
          id: 'm2',
          title: 'Đợt 2 — Mở rộng vùng hỗ trợ',
          description: 'Mở rộng hỗ trợ đến 700 hộ tại các xã lân cận.',
          plannedAmount: 300_000_000,
          releaseCondition: 'Báo cáo hoàn tất đợt 1 + biên bản bàn giao.',
        },
        {
          id: 'm3',
          title: 'Đợt 3 — Ổn định sau cứu trợ',
          description: 'Hỗ trợ tái thiết và phân phối cho 500 hộ còn lại.',
          plannedAmount: 350_000_000,
          releaseCondition: 'Báo cáo đợt 2 + minh chứng phân phối.',
        },
      ],
      acknowledgements: {
        legalRead: true,
        slaAccepted: true,
        overfundPolicyAccepted: true,
        termsAccepted: true,
        transparencyAccepted: true,
        legalLiabilityAccepted: true,
      },
      otpSigned: true,
    },
  },
  {
    id: 'CAMP_NF_2',
    createdAt: '2026-04-22T08:15:00Z',
    status: 'PENDING',
    type: 'APPROVE_CAMPAIGN',
    campaignId: 9002,
    campaignTitle: 'Xây trường học vùng cao Hà Giang',
    requesterName: 'LE THI HUONG',
    description: 'Xây mới 2 phòng học kiên cố cho điểm trường Lùng Tám, Quản Bạ.',
    category: 'Giáo dục',
    kycVerified: true,
    bankVerified: true,
    fundOwnerId: 102,
    newFlowData: {
      eligibility: {
        kycStatus: 'APPROVED',
        kycFullName: 'LE THI HUONG',
        bankInfo: {
          bankCode: 'VCB',
          bankName: 'Ngân hàng TMCP Ngoại Thương Việt Nam',
          accountHolderName: 'LE THI HUONG',
          accountNumber: '0071000234567',
        },
        credibilityFiles: [
          { id: 'f3', name: 'cv-thien-nguyen-huong.pdf', sizeKb: 1200 },
        ],
        credibilityPitch:
          'Giáo viên tình nguyện 5 năm tại Hà Giang, đã vận động xây 1 điểm trường năm 2024.',
      },
      campaignImages: [
        { id: 'img4', url: 'https://images.unsplash.com/photo-1497375638960-ca368c7231e4?w=600&h=400&fit=crop' },
        { id: 'img5', url: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&h=400&fit=crop' },
      ],
      coverImageId: 'img4',
      objective:
        'Xây mới 2 phòng học kiên cố (mỗi phòng 36m²) tại điểm trường Lùng Tám, thay thế phòng tạm bợ hiện tại, đảm bảo an toàn cho 60 học sinh.',
      targetAmount: 500_000_000,
      startDate: '2026-05-01',
      endDate: '2026-08-31',
      region: 'Quản Bạ, Hà Giang',
      beneficiaryType: 'Học sinh tiểu học dân tộc thiểu số',
      thankMessage: 'Mỗi viên gạch bạn góp là một bước chân đến trường cho trẻ vùng cao.',
      milestones: [
        {
          id: 'm4',
          title: 'Đợt 1 — Khảo sát & nền móng',
          description: 'Khảo sát địa hình, đổ nền móng 2 phòng.',
          plannedAmount: 150_000_000,
          releaseCondition: 'Biên bản khảo sát + bản vẽ kỹ thuật.',
        },
        {
          id: 'm5',
          title: 'Đợt 2 — Xây dựng thô',
          description: 'Thi công tường, mái, cửa.',
          plannedAmount: 250_000_000,
          releaseCondition: 'Ảnh tiến độ + biên bản nghiệm thu nền móng.',
        },
        {
          id: 'm6',
          title: 'Đợt 3 — Hoàn thiện & bàn giao',
          description: 'Sơn, lắp điện, bàn ghế, bàn giao trường.',
          plannedAmount: 100_000_000,
          releaseCondition: 'Biên bản nghiệm thu xây thô + biên bản bàn giao.',
        },
      ],
      acknowledgements: {
        legalRead: true,
        slaAccepted: true,
        overfundPolicyAccepted: true,
        termsAccepted: true,
        transparencyAccepted: true,
        legalLiabilityAccepted: true,
      },
      otpSigned: true,
    },
  },
  {
    id: 'CAMP_NF_3',
    createdAt: '2026-04-23T14:45:00Z',
    status: 'PENDING',
    type: 'APPROVE_CAMPAIGN',
    campaignId: 9003,
    campaignTitle: 'Phẫu thuật tim cho trẻ em nghèo',
    requesterName: 'TRAN DINH KHAI',
    description: 'Hỗ trợ chi phí phẫu thuật tim bẩm sinh cho 10 trẻ em hoàn cảnh khó khăn.',
    category: 'Y tế',
    kycVerified: false,
    bankVerified: false,
    fundOwnerId: 103,
    newFlowData: {
      eligibility: {
        kycStatus: 'PENDING',
        kycFullName: 'TRAN DINH KHAI',
        bankInfo: {
          bankCode: 'TCB',
          bankName: 'Ngân hàng TMCP Kỹ Thương Việt Nam',
          accountHolderName: 'TRAN DINH KHAI',
          accountNumber: '19038xxxxxx',
        },
        credibilityFiles: [],
        credibilityPitch: 'Bác sĩ nội trú Bệnh viện Nhi Trung ương, 3 năm tham gia chương trình Trái Tim cho Em.',
      },
      campaignImages: [
        { id: 'img6', url: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&h=400&fit=crop' },
      ],
      coverImageId: 'img6',
      objective:
        'Hỗ trợ toàn bộ chi phí phẫu thuật tim bẩm sinh (từ 50-80 triệu/ca) cho 10 trẻ em có hoàn cảnh đặc biệt khó khăn.',
      targetAmount: 700_000_000,
      startDate: '2026-05-15',
      endDate: '2026-12-31',
      region: 'Toàn quốc',
      beneficiaryType: 'Trẻ em dưới 16 tuổi mắc bệnh tim bẩm sinh',
      thankMessage: 'Bạn vừa góp nhịp đập cho một trái tim nhỏ. Cảm ơn bạn vô cùng!',
      milestones: [
        {
          id: 'm7',
          title: 'Đợt 1 — 4 ca đầu tiên',
          description: 'Phẫu thuật 4 ca ưu tiên nhất.',
          plannedAmount: 280_000_000,
          releaseCondition: 'Xác nhận hồ sơ bệnh nhân + lịch mổ từ bệnh viện.',
        },
        {
          id: 'm8',
          title: 'Đợt 2 — 6 ca tiếp theo',
          description: 'Phẫu thuật 6 ca còn lại.',
          plannedAmount: 420_000_000,
          releaseCondition: 'Báo cáo đợt 1 + xác nhận hồ sơ đợt 2.',
        },
      ],
      acknowledgements: {
        legalRead: true,
        slaAccepted: true,
        overfundPolicyAccepted: false,
        termsAccepted: true,
        transparencyAccepted: false,
        legalLiabilityAccepted: false,
      },
      otpSigned: false,
    },
  },
];
