export const API_ENDPOINTS = {
  CAMPAIGNS: {
    BASE: "/api/campaigns",
    BY_ID: (id: number | string) => `/api/campaigns/${id}`,
    BY_FUND_OWNER: (fundOwnerId: number | string) =>
      `/api/campaigns/fund-owner/${fundOwnerId}`,
    BY_FUND_OWNER_PAGINATED: (fundOwnerId: number | string) =>
      `/api/campaigns/fund-owner/${fundOwnerId}/paginated`,
    BY_STATUS: (status: string) => `/api/campaigns/status/${status}`,
    BY_CATEGORY: (categoryId: number | string) => `/api/campaigns/category/${categoryId}`,
    REVIEW: (id: number | string) => `/api/campaigns/${id}/review`,
    UPDATE_BALANCE: (id: number | string) => `/api/campaigns/${id}/update-balance`,
    PAUSE: (id: number | string) => `/api/campaigns/${id}/pause`,
    CLOSE: (id: number | string) => `/api/campaigns/${id}/close`,
  },
  CAMPAIGN_FOLLOWS: {
    BASE: "/api/campaign-follows",
    FOLLOW: (id: number | string) => `/api/campaign-follows/${id}`,
    UNFOLLOW: (id: number | string) => `/api/campaign-follows/${id}`,
    FOLLOWERS: (id: number | string) => `/api/campaign-follows/${id}/followers`,
    COUNT: (id: number | string) => `/api/campaign-follows/${id}/count`,
    IS_FOLLOWING: (id: number | string) => `/api/campaign-follows/${id}/me`,
    MY_FOLLOWS: "/api/campaign-follows/me",
  },
  FUNDRAISING_GOALS: {
    BASE: "/api/fundraising-goals",
    BY_CAMPAIGN: (campaignId: number | string) => `/api/fundraising-goals/campaign/${campaignId}`,
  },
  FEED_POSTS: {
    BASE: "/api/feed-posts",
    MY: "/api/feed-posts/my",
    BY_ID: (id: number | string) => `/api/feed-posts/${id}`,
    BY_AUTHOR: (authorId: number | string) => `/api/feed-posts/author/${authorId}`,
    LIKE: (id: number | string) => `/api/feed-posts/${id}/like`,
    COMMENTS: (postId: number | string) => `/api/feed-posts/${postId}/comments`,
    COMMENT_BY_ID: (commentId: number | string) => `/api/feed-posts/comments/${commentId}`,
    COMMENT_LIKE: (commentId: number | string) => `/api/feed-posts/comments/${commentId}/like`,
    ADMIN_ALL: "/api/feed-posts/admin",
    ADMIN_DELETE: (id: number | string) => `/api/feed-posts/admin/${id}`,
    ADMIN_PIN: (id: number | string) => `/api/feed-posts/admin/${id}/pin`,
    ADMIN_LOCK: (id: number | string) => `/api/feed-posts/admin/${id}/lock`,
    ADMIN_APPROVE: (id: number | string) => `/api/feed-posts/admin/${id}/approve`,
    ADMIN_REJECT: (id: number | string) => `/api/feed-posts/admin/${id}/reject`,
    ADMIN_HIDE: (id: number | string) => `/api/feed-posts/admin/${id}/hide`,
    ADMIN_STATUS: (id: number | string) => `/api/feed-posts/admin/${id}/status`,
    STATUS: (id: number | string) => `/api/feed-posts/${id}/status`,
  },
  FLAGS: {
    BASE: "/api/flags",
    PENDING: "/api/flags/pending",
    BY_POST: (postId: number | string) => `/api/flags/posts/${postId}`,
    BY_CAMPAIGN: (campaignId: number | string) => `/api/flags/campaigns/${campaignId}`,
    MY_FLAGS: "/api/flags/me",
    BY_ID: (id: number | string) => `/api/flags/${id}`,
    REVIEW: (id: number | string) => `/api/flags/${id}/review`,
  },
  CHAT: {
    CONVERSATIONS: "/api/chat/conversations",
    BY_CAMPAIGN: (campaignId: string | number) => `/api/chat/conversations/campaign/${campaignId}`,
    MESSAGES: (id: string | number) => `/api/chat/conversations/${id}/messages`,
  },
  USERS: {
    BASE: "/api/users",
    BY_ID: (id: number | string) => `/api/users/${id}`,
    BAN: (id: number | string) => `/api/users/${id}/ban`,
    UNBAN: (id: number | string) => `/api/users/${id}/unban`,
    UPGRADE_TO_FUND_OWNER: (id: number | string) => `/api/users/${id}/upgrade-role`,
    UPGRADE_TO_FUND_DONOR: (id: number | string) => `/api/users/${id}/upgrade-to-fund-donor`,
    STAFF: "/api/users/staff",
    EXPORT: "/api/users/export",
    IMPORT: "/api/users/import",
    IMPORT_TEMPLATE: "/api/users/import/template",
  },
  GOALS: {
    BASE: "/api/fundraising-goals",
    BY_ID: (id: number | string) => `/api/fundraising-goals/${id}`,
    BY_CAMPAIGN: (campaignId: number | string) =>
      `/api/fundraising-goals/campaign/${campaignId}`,
  },
  BANK_ACCOUNTS: {
    BASE: "/api/bank-accounts",
    BY_ID: (id: number | string) => `/api/bank-accounts/${id}`,
    BY_USER: (userId: number | string) => `/api/bank-accounts/user/${userId}`,
    MY_ACCOUNTS: "/api/bank-accounts",
    CHECK_EXISTS: "/api/bank-accounts/check-exists",
  },
  EXPENDITURES: {
    BASE: "/api/expenditures",
    BY_CAMPAIGN: (campaignId: number | string) => `/api/expenditures/campaign/${campaignId}`,
    BY_ID: (id: number | string) => `/api/expenditures/${id}`,
    ITEMS: (id: number | string) => `/api/expenditures/${id}/items`,
    UPDATE_STATUS: (id: number | string) => `/api/expenditures/${id}/status`,
  },
  APPOINTMENTS: {
    BASE: "/api/appointments",
    BY_ID: (id: number | string) => `/api/appointments/${id}`,
    BY_DONOR: (donorId: number | string) => `/api/appointments/donor/${donorId}`,
    BY_STAFF: (staffId: number | string) => `/api/appointments/staff/${staffId}`,
    UPDATE_STATUS: (id: number | string) => `/api/appointments/${id}/status`,
  },
  CAMPAIGN_CATEGORIES: {
    BASE: "/api/campaign-categories",
    BY_ID: (id: number | string) => `/api/campaign-categories/${id}`,
  },
  PAYMENTS: {
    BASE: "/api/payments",
    CREATE: "/api/payments/create",
    BY_DONATION_ID: (id: number | string) => `/api/payments/donation/${id}`,
    VERIFY: (id: number | string) => `/api/payments/donation/${id}/verify`,
    CHECK_ITEM_LIMIT: (id: number | string) => `/api/payments/expenditure-item/${id}/check`,
    CAMPAIGN_PROGRESS: (campaignId: number | string) => `/api/payments/campaign/${campaignId}/progress`,
    CAMPAIGN_RECENT_DONATIONS: (campaignId: number | string) => `/api/payments/campaign/${campaignId}/recent-donations`,
    CAMPAIGN_ANALYTICS: (campaignId: number | string) => `/api/payments/campaign/${campaignId}/analytics`,
    DONATION_SUMMARY: "/api/payments/donations/summary",
  },
  TASKS: {
    BASE: "/api/admin/tasks",
    BY_STAFF: (staffId: number | string) => `/api/admin/tasks/staff/${staffId}`,
    REASSIGN: (taskId: number | string) => `/api/admin/tasks/${taskId}/reassign`,
    BY_CAMPAIGN: (campaignId: number | string) => `/api/admin/tasks/campaign/${campaignId}`,
  },
  NOTIFICATIONS: {
    BASE: "/api/notifications",
    BY_USER: (userId: number | string) => `/api/notifications/user/${userId}`,
    LATEST: (userId: number | string) => `/api/notifications/user/${userId}/latest`,
    UNREAD_COUNT: (userId: number | string) => `/api/notifications/user/${userId}/unread-count`,
    MARK_AS_READ: (id: number | string) => `/api/notifications/${id}/read`,
  },
  USER_POST_SEEN: {
    BASE: "/api/user-post-seen",
  },
} as const;
