import type { IconKey } from "@/types/module"
import type { LucideIcon } from "lucide-react"

import {
    LayoutDashboard,
    Users,
    User,
    Shield,
    Settings,
    List,
    Folder,
    Layers,
    Calendar,
    BookOpen,
    ClipboardCheck,
    Home,
    Star,
    Building,
    MapPin,
    TrendingUp,
    GraduationCap,
    Heart,
    DollarSign,
    Target,
    CreditCard,
    UserCheck,
    Tag,
    MessageCircle,
    MessageSquare,
    Rss,
    Bell,
    History,
    Database,
    BarChart,
} from "lucide-react"

export const iconMap: Record<IconKey, LucideIcon> = {
    dashboard: LayoutDashboard,
    users: Users,
    person: User,
    people: Users,
    security: Shield,
    settings: Settings,
    menu: List,
    folder: Folder,
    layers: Layers,
    calendar: Calendar,
    "book-open": BookOpen,
    "clipboard-check": ClipboardCheck,
    home: Home,
    star: Star,
    building: Building,
    "map-pin": MapPin,
    "trending-up": TrendingUp,
    "graduation-cap": GraduationCap,
    heart: Heart,
    "dollar-sign": DollarSign,
    target: Target,
    "credit-card": CreditCard,
    "user-check": UserCheck,
    tag: Tag,
    "message-circle": MessageCircle,
    "message-square": MessageSquare,
    rss: Rss,
    bell: Bell,
    history: History,
    database: Database,
    "chart-bar": BarChart,
}
